### ISSUE TITLE
怎么启动啊。。。

### ISSUE THREAD

**Issue by bangbang2333** [youlookwhat/DesignPattern#19]

**Comment by youlookwhat** [comment]
将项目clone下来，用AS运行就起来了啊，或者通过最下面的链接下载

**Comment by bangbang2333** [comment]
> 将项目clone下来，用AS运行就起来了啊，或者通过最下面的链接下载

idea可以启动吗，没搞过这种项目呀

**Comment by youlookwhat** [comment]
idea没试过，应该比较麻烦，这是个安卓的项目啊，不过项目里面基本是说明解释也没什么，你是安卓手机吗，我可以发个apk给你下载

**Comment by bangbang2333** [comment]
安装了As，编译下载了半天，貌似还要修改bios，我裂开了。。。大佬给我发apk吧，




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "景彬"<notifications@github.com&gt;; 
发送时间: 2020年3月9日(星期一) 晚上6:43
收件人: "youlookwhat/DesignPattern"<DesignPattern@noreply.github.com&gt;; 
抄送: "just"<1767722806@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [youlookwhat/DesignPattern] 怎么启动啊。。。 (#19)




idea没试过，应该比较麻烦，这是个安卓的项目啊，不过项目里面基本是说明解释也没什么，你是安卓手机吗，我可以发个apk给你下载

**Comment by youlookwhat** [comment]
好的 稍等

**Comment by youlookwhat** [comment]
http://d.6short.com/designpattern

在这个链接里下载就好了

**Comment by bangbang2333** [comment]
close
