### ISSUE TITLE
需要 PR 切换到 androidx 吗

### ISSUE THREAD

**Issue by sunnyswag** [youlookwhat/DesignPattern#27]

**Comment by youlookwhat** [comment]
我抽时间换成 androidx ，也还好

**Comment by youlookwhat** [comment]
已经升级到 AndroidX ,[update to AndroidX](https://github.com/youlookwhat/DesignPattern/commit/a695b053e9dbbd591ddcccda2c3a40ff87fe65cd)

拉最新的代码查看即可
